/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */
export declare const controllers: {
    Addons: () => Promise<typeof import("#controllers/addons_controller")>;
    admin: {
        Debug: () => Promise<typeof import("#controllers/admin/debug_controller")>;
    };
    Analytics: () => Promise<typeof import("#controllers/analytics_controller")>;
    Audits: () => Promise<typeof import("#controllers/audits_controller")>;
    Auth: () => Promise<typeof import("#controllers/auth_controller")>;
    BlogCategories: () => Promise<typeof import("#controllers/blog_categories_controller")>;
    BlogPosts: () => Promise<typeof import("#controllers/blog_posts_controller")>;
    ConfirmDeleteCustomUser: () => Promise<typeof import("#controllers/confirm_delete_custom_user_controller")>;
    Dashboard: () => Promise<typeof import("#controllers/dashboard_controller")>;
    DbBackups: () => Promise<typeof import("#controllers/db_backups_controller")>;
    Emails: () => Promise<typeof import("#controllers/emails_controller")>;
    EmailsPage: () => Promise<typeof import("#controllers/emails_page_controller")>;
    HealthChecks: () => Promise<typeof import("#controllers/health_checks_controller")>;
    LeaseableEntities: () => Promise<typeof import("#controllers/leaseable_entities_controller")>;
    Leases: () => Promise<typeof import("#controllers/leases_controller")>;
    LogsPage: () => Promise<typeof import("#controllers/logs_page_controller")>;
    Members: () => Promise<typeof import("#controllers/members_controller")>;
    Notifications: () => Promise<typeof import("#controllers/notifications_controller")>;
    OrgActions: () => Promise<typeof import("#controllers/org_actions_controller")>;
    Orgs: () => Promise<typeof import("#controllers/orgs_controller")>;
    PushNotifications: () => Promise<typeof import("#controllers/push_notifications_controller")>;
    Railway: () => Promise<typeof import("#controllers/railway_controller")>;
    ServerStats: () => Promise<typeof import("#controllers/server_stats_controller")>;
    Servers: () => Promise<typeof import("#controllers/servers_controller")>;
    Sessions: () => Promise<typeof import("#controllers/sessions_controller")>;
    TeamInvitations: () => Promise<typeof import("#controllers/team_invitations_controller")>;
    TeamsPage: () => Promise<typeof import("#controllers/teams_page_controller")>;
    TwoFactor: () => Promise<typeof import("#controllers/two_factor_controller")>;
    Users: () => Promise<typeof import("#controllers/users_controller")>;
};
