/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Addons: () => import('#controllers/addons_controller'),
  Analytics: () => import('#controllers/analytics_controller'),
  Audits: () => import('#controllers/audits_controller'),
  Auth: () => import('#controllers/auth_controller'),
  BlogAuthors: () => import('#controllers/blog_authors_controller'),
  BlogCategories: () => import('#controllers/blog_categories_controller'),
  BlogPosts: () => import('#controllers/blog_posts_controller'),
  BlogTags: () => import('#controllers/blog_tags_controller'),
  ConfirmDeleteCustomUser: () => import('#controllers/confirm_delete_custom_user_controller'),
  Dashboard: () => import('#controllers/dashboard_controller'),
  DbBackups: () => import('#controllers/db_backups_controller'),
  Emails: () => import('#controllers/emails_controller'),
  EmailsPage: () => import('#controllers/emails_page_controller'),
  HealthChecks: () => import('#controllers/health_checks_controller'),
  LeaseableEntities: () => import('#controllers/leaseable_entities_controller'),
  Leases: () => import('#controllers/leases_controller'),
  LogsPage: () => import('#controllers/logs_page_controller'),
  Members: () => import('#controllers/members_controller'),
  Notifications: () => import('#controllers/notifications_controller'),
  OrgActions: () => import('#controllers/org_actions_controller'),
  Orgs: () => import('#controllers/orgs_controller'),
  PushNotifications: () => import('#controllers/push_notifications_controller'),
  Railway: () => import('#controllers/railway_controller'),
  Servers: () => import('#controllers/servers_controller'),
  Sessions: () => import('#controllers/sessions_controller'),
  TeamInvitations: () => import('#controllers/team_invitations_controller'),
  TeamsPage: () => import('#controllers/teams_page_controller'),
  TwoFactor: () => import('#controllers/two_factor_controller'),
  Users: () => import('#controllers/users_controller'),
}
