export enum FileStoreRoutes {
  LEASE_CONTRACTS = 'documents/leases',
  TENANT_DOCS = 'documents/tenant-docs',
  SIGNATURES = 'documents/signatures',
  PROPERTY_DOCS = 'documents/property-docs',
  PROPERTY_IMAGES = 'photos/property-images',
  PROPERTY_LEASE_DOCS = 'documents/property-lease-docs',
  COMPLIANCE_DOCS = 'documents/compliance-docs',
  COMPLIANCE_IMAGES = 'photos/compliance-images',
  EXPENSES = 'documents/expenses',
  INVOICE_DOCS = 'documents/invoice-docs',
  RECEIPT_DOCS = 'documents/receipt-docs',
  DOCUMENTS = 'documents/files',
  PHOTOS = 'photos',
  TENANT_PROFILE_IMAGES = '/documents/tenant-profile-images',
  REPORTS_DOCS = 'documents/reports-docs',
  REPORTS_IMAGES = 'photos/reports-images',
  PAYOUT_STATEMENTS = 'documents/payout-statements',
  INVENTORY_IMAGES = 'photos/inventory-images',
  BROADCASTS = 'documents/broadcasts',
  SALES = 'documents/sales',
  COMPANY_LOGOS = 'company-logos',
  COMPANY_FAVICONS = 'company-favicons',
  BLOG_IMAGES = 'blog-images',
}
