/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AddOnSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'shortDescription', 'longDescription', 'priceAmount', 'priceCurrency', 'billingType', 'stripePriceId', 'features', 'isActive', 'sortOrder', 'createdAt', 'updatedAt'] as const
  $columns = AddOnSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare shortDescription: string | null
  @column()
  declare longDescription: string | null
  @column()
  declare priceAmount: string | null
  @column()
  declare priceCurrency: string | null
  @column()
  declare billingType: string
  @column()
  declare stripePriceId: string | null
  @column()
  declare features: any | null
  @column()
  declare isActive: boolean
  @column()
  declare sortOrder: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuditSchema extends BaseModel {
  static $columns = ['id', 'userType', 'userId', 'event', 'auditableType', 'auditableId', 'oldValues', 'newValues', 'metadata', 'createdAt', 'updatedAt'] as const
  $columns = AuditSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userType: string | null
  @column()
  declare userId: string | null
  @column()
  declare event: string
  @column()
  declare auditableType: string
  @column()
  declare auditableId: string
  @column()
  declare oldValues: any | null
  @column()
  declare newValues: any | null
  @column()
  declare metadata: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class AuthAccessTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'type', 'name', 'hash', 'abilities', 'createdAt', 'updatedAt', 'lastUsedAt', 'expiresAt'] as const
  $columns = AuthAccessTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column()
  declare type: string
  @column()
  declare name: string | null
  @column()
  declare hash: string
  @column()
  declare abilities: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
}

export class BlogAuthorSchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'email', 'avatarUrl', 'bio', 'createdAt', 'updatedAt'] as const
  $columns = BlogAuthorSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare email: string | null
  @column()
  declare avatarUrl: string | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlogCategorySchema extends BaseModel {
  static $columns = ['id', 'name', 'slug', 'description', 'createdAt', 'updatedAt'] as const
  $columns = BlogCategorySchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare name: string
  @column()
  declare slug: string
  @column()
  declare description: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class BlogPostSchema extends BaseModel {
  static $columns = ['id', 'title', 'slug', 'summary', 'body', 'thumbnailUrl', 'coverImageUrl', 'categoryId', 'publishedAt', 'createdAt', 'updatedAt'] as const
  $columns = BlogPostSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare title: string
  @column()
  declare slug: string
  @column()
  declare summary: string | null
  @column()
  declare body: string | null
  @column()
  declare thumbnailUrl: string | null
  @column()
  declare coverImageUrl: string | null
  @column()
  declare categoryId: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DeleteAccountRequestSchema extends BaseModel {
  static $columns = ['id', 'orgId', 'tokenHash', 'expiresAt', 'createdAt', 'updatedAt'] as const
  $columns = DeleteAccountRequestSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare orgId: string
  @column()
  declare tokenHash: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class NotificationSchema extends BaseModel {
  static $columns = ['id', 'userId', 'title', 'message', 'type', 'read', 'readAt', 'actions', 'data', 'createdAt', 'updatedAt'] as const
  $columns = NotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string | null
  @column()
  declare title: string
  @column()
  declare message: string
  @column()
  declare type: string
  @column()
  declare read: boolean | null
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare actions: any | null
  @column()
  declare data: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PasswordResetSchema extends BaseModel {
  static $columns = ['id', 'userId', 'email', 'token', 'createdAt', 'updatedAt', 'expiresAt', 'type'] as const
  $columns = PasswordResetSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare userId: string
  @column()
  declare email: string
  @column()
  declare token: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare type: string
}

export class PushNotificationSchema extends BaseModel {
  static $columns = ['id', 'targetType', 'targetUserIds', 'title', 'description', 'imageUrl', 'url', 'scheduledAt', 'sentAt', 'status', 'oneSignalResponse', 'errorMessage', 'createdAt', 'updatedAt'] as const
  $columns = PushNotificationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare targetType: string
  @column()
  declare targetUserIds: any | null
  @column()
  declare title: string
  @column()
  declare description: string
  @column()
  declare imageUrl: string | null
  @column()
  declare url: string | null
  @column.dateTime()
  declare scheduledAt: DateTime | null
  @column.dateTime()
  declare sentAt: DateTime | null
  @column()
  declare status: string
  @column()
  declare oneSignalResponse: any | null
  @column()
  declare errorMessage: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['key', 'points', 'expire'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare key: string
  @column()
  declare points: number
  @column()
  declare expire: bigint | number | null
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['id', 'tokenableId', 'hash', 'createdAt', 'updatedAt', 'expiresAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: string
  @column()
  declare hash: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
}

export class SessionSchema extends BaseModel {
  static $columns = ['id', 'userId', 'ipAddress', 'userAgent', 'deviceType', 'browser', 'os', 'location', 'isCurrent', 'lastActivity', 'createdAt', 'updatedAt'] as const
  $columns = SessionSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string
  @column()
  declare ipAddress: string | null
  @column()
  declare userAgent: string | null
  @column()
  declare deviceType: string | null
  @column()
  declare browser: string | null
  @column()
  declare os: string | null
  @column()
  declare location: string | null
  @column()
  declare isCurrent: boolean | null
  @column.dateTime()
  declare lastActivity: DateTime
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class TeamInvitationSchema extends BaseModel {
  static $columns = ['id', 'email', 'role', 'tokenHash', 'invitedByUserId', 'expiresAt', 'acceptedAt', 'acceptedByUserId', 'invitedUserRole', 'allowedPages', 'createdAt', 'updatedAt', 'enableProdAccess'] as const
  $columns = TeamInvitationSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare email: string
  @column()
  declare role: string
  @column()
  declare tokenHash: string
  @column()
  declare invitedByUserId: string
  @column.dateTime()
  declare expiresAt: DateTime
  @column.dateTime()
  declare acceptedAt: DateTime | null
  @column()
  declare acceptedByUserId: string | null
  @column()
  declare invitedUserRole: string
  @column()
  declare allowedPages: any | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare enableProdAccess: boolean | null
}

export class TeamMemberSchema extends BaseModel {
  static $columns = ['id', 'userId', 'role', 'allowedPages', 'enableProdAccess', 'createdAt', 'updatedAt', 'dataAccessMode', 'allowedLeaseableEntityIds', 'allowedLeaseIds', 'propertiesAccessMode', 'leasesAccessMode', 'dataAccessExpiresAt'] as const
  $columns = TeamMemberSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare userId: string
  @column()
  declare role: string
  @column()
  declare allowedPages: any | null
  @column()
  declare enableProdAccess: boolean | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare dataAccessMode: string | null
  @column()
  declare allowedLeaseableEntityIds: any | null
  @column()
  declare allowedLeaseIds: any | null
  @column()
  declare propertiesAccessMode: string | null
  @column()
  declare leasesAccessMode: string | null
  @column.dateTime()
  declare dataAccessExpiresAt: DateTime | null
}

export class UserSchema extends BaseModel {
  static $columns = ['id', 'fullName', 'email', 'password', 'role', 'avatar', 'googleData', 'token', 'pendingEmail', 'emailVerified', 'emailVerifiedAt', 'emailChangeToken', 'settings', 'twoFactorEnabled', 'twoFactorSecret', 'twoFactorRecoveryCodes', 'lastLoginAt', 'createdAt', 'updatedAt', 'isGodAdmin', 'enableProdAccess'] as const
  $columns = UserSchema.$columns
  @column({ isPrimary: true })
  declare id: string
  @column()
  declare fullName: string | null
  @column()
  declare email: string
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare role: string
  @column()
  declare avatar: any | null
  @column()
  declare googleData: any | null
  @column()
  declare token: string | null
  @column()
  declare pendingEmail: string | null
  @column()
  declare emailVerified: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare emailChangeToken: string | null
  @column()
  declare settings: any | null
  @column()
  declare twoFactorEnabled: boolean | null
  @column()
  declare twoFactorSecret: string | null
  @column()
  declare twoFactorRecoveryCodes: string | null
  @column.dateTime()
  declare lastLoginAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare isGodAdmin: boolean | null
  @column()
  declare enableProdAccess: boolean
}
