/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="../../adonisrc.ts" />
/// <reference path="../../config/attachment.ts" />
/// <reference path="../../config/auditing.ts" />
/// <reference path="../../config/auth.ts" />
/// <reference path="../../config/boss.ts" />
/// <reference path="../../config/cache.ts" />
/// <reference path="../../config/drive.ts" />
/// <reference path="../../config/hash.ts" />
/// <reference path="../../config/limiter.ts" />
/// <reference path="../../config/logger.ts" />
/// <reference path="../../config/mail.ts" />
/// <reference path="../../config/otel.ts" />
/// <reference path="../../config/server_stats.ts" />
/// <reference path="../../config/swagger.ts" />
/// <reference path="../../config/transmit.ts" />
