/* eslint-disable prettier/prettier */
import type { AdonisEndpoint } from '@tuyau/core/types'
import type { Registry } from './schema.d.ts'
import type { ApiDefinition } from './tree.d.ts'

const placeholder: any = {}

const routes = {
  'server-stats.dashboard': {
    methods: ["GET","HEAD"],
    pattern: '/stats',
    tokens: [{"old":"/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['server-stats.dashboard']['types'],
  },
  'server-stats.overview': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/overview',
    tokens: [{"old":"/stats/api/overview","type":0,"val":"stats","end":""},{"old":"/stats/api/overview","type":0,"val":"api","end":""},{"old":"/stats/api/overview","type":0,"val":"overview","end":""}],
    types: placeholder as Registry['server-stats.overview']['types'],
  },
  'server-stats.overview.chart': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/overview/chart',
    tokens: [{"old":"/stats/api/overview/chart","type":0,"val":"stats","end":""},{"old":"/stats/api/overview/chart","type":0,"val":"api","end":""},{"old":"/stats/api/overview/chart","type":0,"val":"overview","end":""},{"old":"/stats/api/overview/chart","type":0,"val":"chart","end":""}],
    types: placeholder as Registry['server-stats.overview.chart']['types'],
  },
  'server-stats.requests': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/requests',
    tokens: [{"old":"/stats/api/requests","type":0,"val":"stats","end":""},{"old":"/stats/api/requests","type":0,"val":"api","end":""},{"old":"/stats/api/requests","type":0,"val":"requests","end":""}],
    types: placeholder as Registry['server-stats.requests']['types'],
  },
  'server-stats.requests.show': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/requests/:id',
    tokens: [{"old":"/stats/api/requests/:id","type":0,"val":"stats","end":""},{"old":"/stats/api/requests/:id","type":0,"val":"api","end":""},{"old":"/stats/api/requests/:id","type":0,"val":"requests","end":""},{"old":"/stats/api/requests/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['server-stats.requests.show']['types'],
  },
  'server-stats.queries': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/queries',
    tokens: [{"old":"/stats/api/queries","type":0,"val":"stats","end":""},{"old":"/stats/api/queries","type":0,"val":"api","end":""},{"old":"/stats/api/queries","type":0,"val":"queries","end":""}],
    types: placeholder as Registry['server-stats.queries']['types'],
  },
  'server-stats.queries.grouped': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/queries/grouped',
    tokens: [{"old":"/stats/api/queries/grouped","type":0,"val":"stats","end":""},{"old":"/stats/api/queries/grouped","type":0,"val":"api","end":""},{"old":"/stats/api/queries/grouped","type":0,"val":"queries","end":""},{"old":"/stats/api/queries/grouped","type":0,"val":"grouped","end":""}],
    types: placeholder as Registry['server-stats.queries.grouped']['types'],
  },
  'server-stats.queries.explain': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/queries/:id/explain',
    tokens: [{"old":"/stats/api/queries/:id/explain","type":0,"val":"stats","end":""},{"old":"/stats/api/queries/:id/explain","type":0,"val":"api","end":""},{"old":"/stats/api/queries/:id/explain","type":0,"val":"queries","end":""},{"old":"/stats/api/queries/:id/explain","type":1,"val":"id","end":""},{"old":"/stats/api/queries/:id/explain","type":0,"val":"explain","end":""}],
    types: placeholder as Registry['server-stats.queries.explain']['types'],
  },
  'server-stats.events': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/events',
    tokens: [{"old":"/stats/api/events","type":0,"val":"stats","end":""},{"old":"/stats/api/events","type":0,"val":"api","end":""},{"old":"/stats/api/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['server-stats.events']['types'],
  },
  'server-stats.routes': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/routes',
    tokens: [{"old":"/stats/api/routes","type":0,"val":"stats","end":""},{"old":"/stats/api/routes","type":0,"val":"api","end":""},{"old":"/stats/api/routes","type":0,"val":"routes","end":""}],
    types: placeholder as Registry['server-stats.routes']['types'],
  },
  'server-stats.logs': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/logs',
    tokens: [{"old":"/stats/api/logs","type":0,"val":"stats","end":""},{"old":"/stats/api/logs","type":0,"val":"api","end":""},{"old":"/stats/api/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['server-stats.logs']['types'],
  },
  'server-stats.emails': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/emails',
    tokens: [{"old":"/stats/api/emails","type":0,"val":"stats","end":""},{"old":"/stats/api/emails","type":0,"val":"api","end":""},{"old":"/stats/api/emails","type":0,"val":"emails","end":""}],
    types: placeholder as Registry['server-stats.emails']['types'],
  },
  'server-stats.emails.preview': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/emails/:id/preview',
    tokens: [{"old":"/stats/api/emails/:id/preview","type":0,"val":"stats","end":""},{"old":"/stats/api/emails/:id/preview","type":0,"val":"api","end":""},{"old":"/stats/api/emails/:id/preview","type":0,"val":"emails","end":""},{"old":"/stats/api/emails/:id/preview","type":1,"val":"id","end":""},{"old":"/stats/api/emails/:id/preview","type":0,"val":"preview","end":""}],
    types: placeholder as Registry['server-stats.emails.preview']['types'],
  },
  'server-stats.traces': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/traces',
    tokens: [{"old":"/stats/api/traces","type":0,"val":"stats","end":""},{"old":"/stats/api/traces","type":0,"val":"api","end":""},{"old":"/stats/api/traces","type":0,"val":"traces","end":""}],
    types: placeholder as Registry['server-stats.traces']['types'],
  },
  'server-stats.traces.show': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/traces/:id',
    tokens: [{"old":"/stats/api/traces/:id","type":0,"val":"stats","end":""},{"old":"/stats/api/traces/:id","type":0,"val":"api","end":""},{"old":"/stats/api/traces/:id","type":0,"val":"traces","end":""},{"old":"/stats/api/traces/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['server-stats.traces.show']['types'],
  },
  'server-stats.cache': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/cache',
    tokens: [{"old":"/stats/api/cache","type":0,"val":"stats","end":""},{"old":"/stats/api/cache","type":0,"val":"api","end":""},{"old":"/stats/api/cache","type":0,"val":"cache","end":""}],
    types: placeholder as Registry['server-stats.cache']['types'],
  },
  'server-stats.cache.show': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/cache/:key',
    tokens: [{"old":"/stats/api/cache/:key","type":0,"val":"stats","end":""},{"old":"/stats/api/cache/:key","type":0,"val":"api","end":""},{"old":"/stats/api/cache/:key","type":0,"val":"cache","end":""},{"old":"/stats/api/cache/:key","type":1,"val":"key","end":""}],
    types: placeholder as Registry['server-stats.cache.show']['types'],
  },
  'server-stats.jobs': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/jobs',
    tokens: [{"old":"/stats/api/jobs","type":0,"val":"stats","end":""},{"old":"/stats/api/jobs","type":0,"val":"api","end":""},{"old":"/stats/api/jobs","type":0,"val":"jobs","end":""}],
    types: placeholder as Registry['server-stats.jobs']['types'],
  },
  'server-stats.jobs.show': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/jobs/:id',
    tokens: [{"old":"/stats/api/jobs/:id","type":0,"val":"stats","end":""},{"old":"/stats/api/jobs/:id","type":0,"val":"api","end":""},{"old":"/stats/api/jobs/:id","type":0,"val":"jobs","end":""},{"old":"/stats/api/jobs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['server-stats.jobs.show']['types'],
  },
  'server-stats.jobs.retry': {
    methods: ["POST"],
    pattern: '/stats/api/jobs/:id/retry',
    tokens: [{"old":"/stats/api/jobs/:id/retry","type":0,"val":"stats","end":""},{"old":"/stats/api/jobs/:id/retry","type":0,"val":"api","end":""},{"old":"/stats/api/jobs/:id/retry","type":0,"val":"jobs","end":""},{"old":"/stats/api/jobs/:id/retry","type":1,"val":"id","end":""},{"old":"/stats/api/jobs/:id/retry","type":0,"val":"retry","end":""}],
    types: placeholder as Registry['server-stats.jobs.retry']['types'],
  },
  'server-stats.config': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/config',
    tokens: [{"old":"/stats/api/config","type":0,"val":"stats","end":""},{"old":"/stats/api/config","type":0,"val":"api","end":""},{"old":"/stats/api/config","type":0,"val":"config","end":""}],
    types: placeholder as Registry['server-stats.config']['types'],
  },
  'server-stats.filters': {
    methods: ["GET","HEAD"],
    pattern: '/stats/api/filters',
    tokens: [{"old":"/stats/api/filters","type":0,"val":"stats","end":""},{"old":"/stats/api/filters","type":0,"val":"api","end":""},{"old":"/stats/api/filters","type":0,"val":"filters","end":""}],
    types: placeholder as Registry['server-stats.filters']['types'],
  },
  'server-stats.filters.create': {
    methods: ["POST"],
    pattern: '/stats/api/filters',
    tokens: [{"old":"/stats/api/filters","type":0,"val":"stats","end":""},{"old":"/stats/api/filters","type":0,"val":"api","end":""},{"old":"/stats/api/filters","type":0,"val":"filters","end":""}],
    types: placeholder as Registry['server-stats.filters.create']['types'],
  },
  'server-stats.filters.delete': {
    methods: ["DELETE"],
    pattern: '/stats/api/filters/:id',
    tokens: [{"old":"/stats/api/filters/:id","type":0,"val":"stats","end":""},{"old":"/stats/api/filters/:id","type":0,"val":"api","end":""},{"old":"/stats/api/filters/:id","type":0,"val":"filters","end":""},{"old":"/stats/api/filters/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['server-stats.filters.delete']['types'],
  },
  'drive.fs.serve': {
    methods: ["GET","HEAD"],
    pattern: '/uploads/*',
    tokens: [{"old":"/uploads/*","type":0,"val":"uploads","end":""},{"old":"/uploads/*","type":2,"val":"*","end":""}],
    types: placeholder as Registry['drive.fs.serve']['types'],
  },
  'analytics.orgs_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/orgs/stats',
    tokens: [{"old":"/api/v1/analytics/orgs/stats","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/orgs/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/orgs/stats","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/orgs/stats","type":0,"val":"orgs","end":""},{"old":"/api/v1/analytics/orgs/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['analytics.orgs_stats']['types'],
  },
  'analytics.orgs_entities': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/orgs/entities',
    tokens: [{"old":"/api/v1/analytics/orgs/entities","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/orgs/entities","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/orgs/entities","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/orgs/entities","type":0,"val":"orgs","end":""},{"old":"/api/v1/analytics/orgs/entities","type":0,"val":"entities","end":""}],
    types: placeholder as Registry['analytics.orgs_entities']['types'],
  },
  'analytics.users_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/users/stats',
    tokens: [{"old":"/api/v1/analytics/users/stats","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/users/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/users/stats","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/users/stats","type":0,"val":"users","end":""},{"old":"/api/v1/analytics/users/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['analytics.users_stats']['types'],
  },
  'analytics.users_entities': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/users/entities',
    tokens: [{"old":"/api/v1/analytics/users/entities","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/users/entities","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/users/entities","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/users/entities","type":0,"val":"users","end":""},{"old":"/api/v1/analytics/users/entities","type":0,"val":"entities","end":""}],
    types: placeholder as Registry['analytics.users_entities']['types'],
  },
  'analytics.leases_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/leases/stats',
    tokens: [{"old":"/api/v1/analytics/leases/stats","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/leases/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/leases/stats","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/leases/stats","type":0,"val":"leases","end":""},{"old":"/api/v1/analytics/leases/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['analytics.leases_stats']['types'],
  },
  'analytics.leases_entities': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/leases/entities',
    tokens: [{"old":"/api/v1/analytics/leases/entities","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/leases/entities","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/leases/entities","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/leases/entities","type":0,"val":"leases","end":""},{"old":"/api/v1/analytics/leases/entities","type":0,"val":"entities","end":""}],
    types: placeholder as Registry['analytics.leases_entities']['types'],
  },
  'analytics.maintenance_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/maintenance/stats',
    tokens: [{"old":"/api/v1/analytics/maintenance/stats","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/maintenance/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/maintenance/stats","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/maintenance/stats","type":0,"val":"maintenance","end":""},{"old":"/api/v1/analytics/maintenance/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['analytics.maintenance_stats']['types'],
  },
  'analytics.maintenance_entities': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/maintenance/entities',
    tokens: [{"old":"/api/v1/analytics/maintenance/entities","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/maintenance/entities","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/maintenance/entities","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/maintenance/entities","type":0,"val":"maintenance","end":""},{"old":"/api/v1/analytics/maintenance/entities","type":0,"val":"entities","end":""}],
    types: placeholder as Registry['analytics.maintenance_entities']['types'],
  },
  'analytics.activity_stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/activity/stats',
    tokens: [{"old":"/api/v1/analytics/activity/stats","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/activity/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/activity/stats","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/activity/stats","type":0,"val":"activity","end":""},{"old":"/api/v1/analytics/activity/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['analytics.activity_stats']['types'],
  },
  'analytics.activity_entities': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/analytics/activity/entities',
    tokens: [{"old":"/api/v1/analytics/activity/entities","type":0,"val":"api","end":""},{"old":"/api/v1/analytics/activity/entities","type":0,"val":"v1","end":""},{"old":"/api/v1/analytics/activity/entities","type":0,"val":"analytics","end":""},{"old":"/api/v1/analytics/activity/entities","type":0,"val":"activity","end":""},{"old":"/api/v1/analytics/activity/entities","type":0,"val":"entities","end":""}],
    types: placeholder as Registry['analytics.activity_entities']['types'],
  },
  'dashboard.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/stats',
    tokens: [{"old":"/api/v1/dashboard/stats","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['dashboard.stats']['types'],
  },
  'dashboard.recent_activity': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/dashboard/activity',
    tokens: [{"old":"/api/v1/dashboard/activity","type":0,"val":"api","end":""},{"old":"/api/v1/dashboard/activity","type":0,"val":"v1","end":""},{"old":"/api/v1/dashboard/activity","type":0,"val":"dashboard","end":""},{"old":"/api/v1/dashboard/activity","type":0,"val":"activity","end":""}],
    types: placeholder as Registry['dashboard.recent_activity']['types'],
  },
  'leases.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/leases/stats',
    tokens: [{"old":"/api/v1/leases/stats","type":0,"val":"api","end":""},{"old":"/api/v1/leases/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/leases/stats","type":0,"val":"leases","end":""},{"old":"/api/v1/leases/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['leases.stats']['types'],
  },
  'leases.payments': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/leases/:id/payments',
    tokens: [{"old":"/api/v1/leases/:id/payments","type":0,"val":"api","end":""},{"old":"/api/v1/leases/:id/payments","type":0,"val":"v1","end":""},{"old":"/api/v1/leases/:id/payments","type":0,"val":"leases","end":""},{"old":"/api/v1/leases/:id/payments","type":1,"val":"id","end":""},{"old":"/api/v1/leases/:id/payments","type":0,"val":"payments","end":""}],
    types: placeholder as Registry['leases.payments']['types'],
  },
  'leases.activity': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/leases/:id/activity',
    tokens: [{"old":"/api/v1/leases/:id/activity","type":0,"val":"api","end":""},{"old":"/api/v1/leases/:id/activity","type":0,"val":"v1","end":""},{"old":"/api/v1/leases/:id/activity","type":0,"val":"leases","end":""},{"old":"/api/v1/leases/:id/activity","type":1,"val":"id","end":""},{"old":"/api/v1/leases/:id/activity","type":0,"val":"activity","end":""}],
    types: placeholder as Registry['leases.activity']['types'],
  },
  'leaseable_entities.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/leaseable-entities/stats',
    tokens: [{"old":"/api/v1/leaseable-entities/stats","type":0,"val":"api","end":""},{"old":"/api/v1/leaseable-entities/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/leaseable-entities/stats","type":0,"val":"leaseable-entities","end":""},{"old":"/api/v1/leaseable-entities/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['leaseable_entities.stats']['types'],
  },
  'leaseable_entities.leases': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/leaseable-entities/:id/leases',
    tokens: [{"old":"/api/v1/leaseable-entities/:id/leases","type":0,"val":"api","end":""},{"old":"/api/v1/leaseable-entities/:id/leases","type":0,"val":"v1","end":""},{"old":"/api/v1/leaseable-entities/:id/leases","type":0,"val":"leaseable-entities","end":""},{"old":"/api/v1/leaseable-entities/:id/leases","type":1,"val":"id","end":""},{"old":"/api/v1/leaseable-entities/:id/leases","type":0,"val":"leases","end":""}],
    types: placeholder as Registry['leaseable_entities.leases']['types'],
  },
  'leaseable_entities.activity': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/leaseable-entities/:id/activity',
    tokens: [{"old":"/api/v1/leaseable-entities/:id/activity","type":0,"val":"api","end":""},{"old":"/api/v1/leaseable-entities/:id/activity","type":0,"val":"v1","end":""},{"old":"/api/v1/leaseable-entities/:id/activity","type":0,"val":"leaseable-entities","end":""},{"old":"/api/v1/leaseable-entities/:id/activity","type":1,"val":"id","end":""},{"old":"/api/v1/leaseable-entities/:id/activity","type":0,"val":"activity","end":""}],
    types: placeholder as Registry['leaseable_entities.activity']['types'],
  },
  'orgs.stats': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/orgs/stats',
    tokens: [{"old":"/api/v1/orgs/stats","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/stats","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/stats","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/stats","type":0,"val":"stats","end":""}],
    types: placeholder as Registry['orgs.stats']['types'],
  },
  'orgs.store': {
    methods: ["POST"],
    pattern: '/api/v1/orgs',
    tokens: [{"old":"/api/v1/orgs","type":0,"val":"api","end":""},{"old":"/api/v1/orgs","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs","type":0,"val":"orgs","end":""}],
    types: placeholder as Registry['orgs.store']['types'],
  },
  'orgs.update': {
    methods: ["PUT"],
    pattern: '/api/v1/orgs/:id',
    tokens: [{"old":"/api/v1/orgs/:id","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:id","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orgs.update']['types'],
  },
  'org_actions.ban_user': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/ban-user',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/ban-user","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/ban-user","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/ban-user","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/ban-user","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/ban-user","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/ban-user","type":0,"val":"ban-user","end":""}],
    types: placeholder as Registry['org_actions.ban_user']['types'],
  },
  'org_actions.unban_user': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/unban-user',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/unban-user","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/unban-user","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/unban-user","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/unban-user","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/unban-user","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/unban-user","type":0,"val":"unban-user","end":""}],
    types: placeholder as Registry['org_actions.unban_user']['types'],
  },
  'org_actions.make_favourite': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/make-favourite',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/make-favourite","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-favourite","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-favourite","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-favourite","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-favourite","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-favourite","type":0,"val":"make-favourite","end":""}],
    types: placeholder as Registry['org_actions.make_favourite']['types'],
  },
  'org_actions.undo_favourite': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/undo-favourite',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/undo-favourite","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-favourite","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-favourite","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-favourite","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-favourite","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-favourite","type":0,"val":"undo-favourite","end":""}],
    types: placeholder as Registry['org_actions.undo_favourite']['types'],
  },
  'org_actions.make_test_account': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/make-test-account',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/make-test-account","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-test-account","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-test-account","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-test-account","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-test-account","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/make-test-account","type":0,"val":"make-test-account","end":""}],
    types: placeholder as Registry['org_actions.make_test_account']['types'],
  },
  'org_actions.undo_test_account': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/undo-test-account',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/undo-test-account","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-test-account","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-test-account","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-test-account","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-test-account","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/undo-test-account","type":0,"val":"undo-test-account","end":""}],
    types: placeholder as Registry['org_actions.undo_test_account']['types'],
  },
  'org_actions.toggle_sales_account': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/toggle-sales-account',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/toggle-sales-account","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/toggle-sales-account","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/toggle-sales-account","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/toggle-sales-account","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/toggle-sales-account","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/toggle-sales-account","type":0,"val":"toggle-sales-account","end":""}],
    types: placeholder as Registry['org_actions.toggle_sales_account']['types'],
  },
  'org_actions.request_delete_custom_user': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/:orgId/actions/request-delete-custom-user',
    tokens: [{"old":"/api/v1/orgs/:orgId/actions/request-delete-custom-user","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/actions/request-delete-custom-user","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/actions/request-delete-custom-user","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/actions/request-delete-custom-user","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/actions/request-delete-custom-user","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/:orgId/actions/request-delete-custom-user","type":0,"val":"request-delete-custom-user","end":""}],
    types: placeholder as Registry['org_actions.request_delete_custom_user']['types'],
  },
  'org_actions.bulk_make_favourite': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/actions/bulk-make-favourite',
    tokens: [{"old":"/api/v1/orgs/actions/bulk-make-favourite","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/actions/bulk-make-favourite","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/actions/bulk-make-favourite","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/actions/bulk-make-favourite","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/actions/bulk-make-favourite","type":0,"val":"bulk-make-favourite","end":""}],
    types: placeholder as Registry['org_actions.bulk_make_favourite']['types'],
  },
  'org_actions.bulk_undo_favourite': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/actions/bulk-undo-favourite',
    tokens: [{"old":"/api/v1/orgs/actions/bulk-undo-favourite","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-favourite","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-favourite","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-favourite","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-favourite","type":0,"val":"bulk-undo-favourite","end":""}],
    types: placeholder as Registry['org_actions.bulk_undo_favourite']['types'],
  },
  'org_actions.bulk_make_test_account': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/actions/bulk-make-test-account',
    tokens: [{"old":"/api/v1/orgs/actions/bulk-make-test-account","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/actions/bulk-make-test-account","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/actions/bulk-make-test-account","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/actions/bulk-make-test-account","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/actions/bulk-make-test-account","type":0,"val":"bulk-make-test-account","end":""}],
    types: placeholder as Registry['org_actions.bulk_make_test_account']['types'],
  },
  'org_actions.bulk_undo_test_account': {
    methods: ["POST"],
    pattern: '/api/v1/orgs/actions/bulk-undo-test-account',
    tokens: [{"old":"/api/v1/orgs/actions/bulk-undo-test-account","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-test-account","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-test-account","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-test-account","type":0,"val":"actions","end":""},{"old":"/api/v1/orgs/actions/bulk-undo-test-account","type":0,"val":"bulk-undo-test-account","end":""}],
    types: placeholder as Registry['org_actions.bulk_undo_test_account']['types'],
  },
  'org_actions.get_ban_status': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/orgs/:orgId/ban-status',
    tokens: [{"old":"/api/v1/orgs/:orgId/ban-status","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:orgId/ban-status","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:orgId/ban-status","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:orgId/ban-status","type":1,"val":"orgId","end":""},{"old":"/api/v1/orgs/:orgId/ban-status","type":0,"val":"ban-status","end":""}],
    types: placeholder as Registry['org_actions.get_ban_status']['types'],
  },
  'orgs.leases': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/orgs/:id/leases',
    tokens: [{"old":"/api/v1/orgs/:id/leases","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:id/leases","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:id/leases","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:id/leases","type":1,"val":"id","end":""},{"old":"/api/v1/orgs/:id/leases","type":0,"val":"leases","end":""}],
    types: placeholder as Registry['orgs.leases']['types'],
  },
  'orgs.properties': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/orgs/:id/properties',
    tokens: [{"old":"/api/v1/orgs/:id/properties","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:id/properties","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:id/properties","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:id/properties","type":1,"val":"id","end":""},{"old":"/api/v1/orgs/:id/properties","type":0,"val":"properties","end":""}],
    types: placeholder as Registry['orgs.properties']['types'],
  },
  'orgs.activities': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/orgs/:id/activities',
    tokens: [{"old":"/api/v1/orgs/:id/activities","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:id/activities","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:id/activities","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:id/activities","type":1,"val":"id","end":""},{"old":"/api/v1/orgs/:id/activities","type":0,"val":"activities","end":""}],
    types: placeholder as Registry['orgs.activities']['types'],
  },
  'orgs.invoices': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/orgs/:id/invoices',
    tokens: [{"old":"/api/v1/orgs/:id/invoices","type":0,"val":"api","end":""},{"old":"/api/v1/orgs/:id/invoices","type":0,"val":"v1","end":""},{"old":"/api/v1/orgs/:id/invoices","type":0,"val":"orgs","end":""},{"old":"/api/v1/orgs/:id/invoices","type":1,"val":"id","end":""},{"old":"/api/v1/orgs/:id/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['orgs.invoices']['types'],
  },
  'push_notifications.users': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/push-notifications/users',
    tokens: [{"old":"/api/v1/push-notifications/users","type":0,"val":"api","end":""},{"old":"/api/v1/push-notifications/users","type":0,"val":"v1","end":""},{"old":"/api/v1/push-notifications/users","type":0,"val":"push-notifications","end":""},{"old":"/api/v1/push-notifications/users","type":0,"val":"users","end":""}],
    types: placeholder as Registry['push_notifications.users']['types'],
  },
  'api.db_backups.store': {
    methods: ["POST"],
    pattern: '/api/v1/db-backups',
    tokens: [{"old":"/api/v1/db-backups","type":0,"val":"api","end":""},{"old":"/api/v1/db-backups","type":0,"val":"v1","end":""},{"old":"/api/v1/db-backups","type":0,"val":"db-backups","end":""}],
    types: placeholder as Registry['api.db_backups.store']['types'],
  },
  'db_backups.restore': {
    methods: ["POST"],
    pattern: '/api/v1/db-backups/:id/restore',
    tokens: [{"old":"/api/v1/db-backups/:id/restore","type":0,"val":"api","end":""},{"old":"/api/v1/db-backups/:id/restore","type":0,"val":"v1","end":""},{"old":"/api/v1/db-backups/:id/restore","type":0,"val":"db-backups","end":""},{"old":"/api/v1/db-backups/:id/restore","type":1,"val":"id","end":""},{"old":"/api/v1/db-backups/:id/restore","type":0,"val":"restore","end":""}],
    types: placeholder as Registry['db_backups.restore']['types'],
  },
  'emails.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/emails',
    tokens: [{"old":"/api/v1/emails","type":0,"val":"api","end":""},{"old":"/api/v1/emails","type":0,"val":"v1","end":""},{"old":"/api/v1/emails","type":0,"val":"emails","end":""}],
    types: placeholder as Registry['emails.index']['types'],
  },
  'emails.show': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/emails/:id',
    tokens: [{"old":"/api/v1/emails/:id","type":0,"val":"api","end":""},{"old":"/api/v1/emails/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/emails/:id","type":0,"val":"emails","end":""},{"old":"/api/v1/emails/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['emails.show']['types'],
  },
  'railway.projects': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/railway/projects',
    tokens: [{"old":"/api/v1/railway/projects","type":0,"val":"api","end":""},{"old":"/api/v1/railway/projects","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/projects","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/projects","type":0,"val":"projects","end":""}],
    types: placeholder as Registry['railway.projects']['types'],
  },
  'railway.project': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/railway/projects/:id',
    tokens: [{"old":"/api/v1/railway/projects/:id","type":0,"val":"api","end":""},{"old":"/api/v1/railway/projects/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/projects/:id","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/projects/:id","type":0,"val":"projects","end":""},{"old":"/api/v1/railway/projects/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['railway.project']['types'],
  },
  'railway.deployments': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/railway/services/:serviceId/deployments',
    tokens: [{"old":"/api/v1/railway/services/:serviceId/deployments","type":0,"val":"api","end":""},{"old":"/api/v1/railway/services/:serviceId/deployments","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/services/:serviceId/deployments","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/services/:serviceId/deployments","type":0,"val":"services","end":""},{"old":"/api/v1/railway/services/:serviceId/deployments","type":1,"val":"serviceId","end":""},{"old":"/api/v1/railway/services/:serviceId/deployments","type":0,"val":"deployments","end":""}],
    types: placeholder as Registry['railway.deployments']['types'],
  },
  'railway.deployment_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/railway/deployments/:id/logs/runtime',
    tokens: [{"old":"/api/v1/railway/deployments/:id/logs/runtime","type":0,"val":"api","end":""},{"old":"/api/v1/railway/deployments/:id/logs/runtime","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/deployments/:id/logs/runtime","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/deployments/:id/logs/runtime","type":0,"val":"deployments","end":""},{"old":"/api/v1/railway/deployments/:id/logs/runtime","type":1,"val":"id","end":""},{"old":"/api/v1/railway/deployments/:id/logs/runtime","type":0,"val":"logs","end":""},{"old":"/api/v1/railway/deployments/:id/logs/runtime","type":0,"val":"runtime","end":""}],
    types: placeholder as Registry['railway.deployment_logs']['types'],
  },
  'railway.deployment_build_logs': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/railway/deployments/:id/logs/build',
    tokens: [{"old":"/api/v1/railway/deployments/:id/logs/build","type":0,"val":"api","end":""},{"old":"/api/v1/railway/deployments/:id/logs/build","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/deployments/:id/logs/build","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/deployments/:id/logs/build","type":0,"val":"deployments","end":""},{"old":"/api/v1/railway/deployments/:id/logs/build","type":1,"val":"id","end":""},{"old":"/api/v1/railway/deployments/:id/logs/build","type":0,"val":"logs","end":""},{"old":"/api/v1/railway/deployments/:id/logs/build","type":0,"val":"build","end":""}],
    types: placeholder as Registry['railway.deployment_build_logs']['types'],
  },
  'railway.deployment_restart': {
    methods: ["POST"],
    pattern: '/api/v1/railway/deployments/:id/restart',
    tokens: [{"old":"/api/v1/railway/deployments/:id/restart","type":0,"val":"api","end":""},{"old":"/api/v1/railway/deployments/:id/restart","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/deployments/:id/restart","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/deployments/:id/restart","type":0,"val":"deployments","end":""},{"old":"/api/v1/railway/deployments/:id/restart","type":1,"val":"id","end":""},{"old":"/api/v1/railway/deployments/:id/restart","type":0,"val":"restart","end":""}],
    types: placeholder as Registry['railway.deployment_restart']['types'],
  },
  'railway.deployment_redeploy': {
    methods: ["POST"],
    pattern: '/api/v1/railway/deployments/:id/redeploy',
    tokens: [{"old":"/api/v1/railway/deployments/:id/redeploy","type":0,"val":"api","end":""},{"old":"/api/v1/railway/deployments/:id/redeploy","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/deployments/:id/redeploy","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/deployments/:id/redeploy","type":0,"val":"deployments","end":""},{"old":"/api/v1/railway/deployments/:id/redeploy","type":1,"val":"id","end":""},{"old":"/api/v1/railway/deployments/:id/redeploy","type":0,"val":"redeploy","end":""}],
    types: placeholder as Registry['railway.deployment_redeploy']['types'],
  },
  'railway.service_deploy': {
    methods: ["POST"],
    pattern: '/api/v1/railway/services/:serviceId/deploy',
    tokens: [{"old":"/api/v1/railway/services/:serviceId/deploy","type":0,"val":"api","end":""},{"old":"/api/v1/railway/services/:serviceId/deploy","type":0,"val":"v1","end":""},{"old":"/api/v1/railway/services/:serviceId/deploy","type":0,"val":"railway","end":""},{"old":"/api/v1/railway/services/:serviceId/deploy","type":0,"val":"services","end":""},{"old":"/api/v1/railway/services/:serviceId/deploy","type":1,"val":"serviceId","end":""},{"old":"/api/v1/railway/services/:serviceId/deploy","type":0,"val":"deploy","end":""}],
    types: placeholder as Registry['railway.service_deploy']['types'],
  },
  'dashboard.index': {
    methods: ["GET","HEAD"],
    pattern: '/dashboard',
    tokens: [{"old":"/dashboard","type":0,"val":"dashboard","end":""}],
    types: placeholder as Registry['dashboard.index']['types'],
  },
  'teams_page.index': {
    methods: ["GET","HEAD"],
    pattern: '/teams',
    tokens: [{"old":"/teams","type":0,"val":"teams","end":""}],
    types: placeholder as Registry['teams_page.index']['types'],
  },
  'teams_page.show': {
    methods: ["GET","HEAD"],
    pattern: '/teams/members/:id',
    tokens: [{"old":"/teams/members/:id","type":0,"val":"teams","end":""},{"old":"/teams/members/:id","type":0,"val":"members","end":""},{"old":"/teams/members/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['teams_page.show']['types'],
  },
  'leases.index': {
    methods: ["GET","HEAD"],
    pattern: '/leases',
    tokens: [{"old":"/leases","type":0,"val":"leases","end":""}],
    types: placeholder as Registry['leases.index']['types'],
  },
  'leases.show': {
    methods: ["GET","HEAD"],
    pattern: '/leases/:id',
    tokens: [{"old":"/leases/:id","type":0,"val":"leases","end":""},{"old":"/leases/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leases.show']['types'],
  },
  'leaseable_entities.index': {
    methods: ["GET","HEAD"],
    pattern: '/properties',
    tokens: [{"old":"/properties","type":0,"val":"properties","end":""}],
    types: placeholder as Registry['leaseable_entities.index']['types'],
  },
  'leaseable_entities.show': {
    methods: ["GET","HEAD"],
    pattern: '/properties/:id',
    tokens: [{"old":"/properties/:id","type":0,"val":"properties","end":""},{"old":"/properties/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['leaseable_entities.show']['types'],
  },
  'orgs.index': {
    methods: ["GET","HEAD"],
    pattern: '/orgs',
    tokens: [{"old":"/orgs","type":0,"val":"orgs","end":""}],
    types: placeholder as Registry['orgs.index']['types'],
  },
  'orgs.create': {
    methods: ["GET","HEAD"],
    pattern: '/orgs/create',
    tokens: [{"old":"/orgs/create","type":0,"val":"orgs","end":""},{"old":"/orgs/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['orgs.create']['types'],
  },
  'orgs.edit': {
    methods: ["GET","HEAD"],
    pattern: '/orgs/:id/edit',
    tokens: [{"old":"/orgs/:id/edit","type":0,"val":"orgs","end":""},{"old":"/orgs/:id/edit","type":1,"val":"id","end":""},{"old":"/orgs/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['orgs.edit']['types'],
  },
  'orgs.show': {
    methods: ["GET","HEAD"],
    pattern: '/orgs/:id',
    tokens: [{"old":"/orgs/:id","type":0,"val":"orgs","end":""},{"old":"/orgs/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['orgs.show']['types'],
  },
  'orgs.create_invoice': {
    methods: ["GET","HEAD"],
    pattern: '/orgs/:id/invoices/create',
    tokens: [{"old":"/orgs/:id/invoices/create","type":0,"val":"orgs","end":""},{"old":"/orgs/:id/invoices/create","type":1,"val":"id","end":""},{"old":"/orgs/:id/invoices/create","type":0,"val":"invoices","end":""},{"old":"/orgs/:id/invoices/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['orgs.create_invoice']['types'],
  },
  'orgs.store_invoice': {
    methods: ["POST"],
    pattern: '/orgs/:id/invoices',
    tokens: [{"old":"/orgs/:id/invoices","type":0,"val":"orgs","end":""},{"old":"/orgs/:id/invoices","type":1,"val":"id","end":""},{"old":"/orgs/:id/invoices","type":0,"val":"invoices","end":""}],
    types: placeholder as Registry['orgs.store_invoice']['types'],
  },
  'orgs.create_invoice_line_item': {
    methods: ["GET","HEAD"],
    pattern: '/orgs/:id/invoices/:invoiceId/line-items/create',
    tokens: [{"old":"/orgs/:id/invoices/:invoiceId/line-items/create","type":0,"val":"orgs","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items/create","type":1,"val":"id","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items/create","type":0,"val":"invoices","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items/create","type":1,"val":"invoiceId","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items/create","type":0,"val":"line-items","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['orgs.create_invoice_line_item']['types'],
  },
  'orgs.store_invoice_line_item': {
    methods: ["POST"],
    pattern: '/orgs/:id/invoices/:invoiceId/line-items',
    tokens: [{"old":"/orgs/:id/invoices/:invoiceId/line-items","type":0,"val":"orgs","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items","type":1,"val":"id","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items","type":0,"val":"invoices","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items","type":1,"val":"invoiceId","end":""},{"old":"/orgs/:id/invoices/:invoiceId/line-items","type":0,"val":"line-items","end":""}],
    types: placeholder as Registry['orgs.store_invoice_line_item']['types'],
  },
  'push_notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/push-notifications',
    tokens: [{"old":"/push-notifications","type":0,"val":"push-notifications","end":""}],
    types: placeholder as Registry['push_notifications.index']['types'],
  },
  'push_notifications.create': {
    methods: ["GET","HEAD"],
    pattern: '/push-notifications/create',
    tokens: [{"old":"/push-notifications/create","type":0,"val":"push-notifications","end":""},{"old":"/push-notifications/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['push_notifications.create']['types'],
  },
  'push_notifications.store': {
    methods: ["POST"],
    pattern: '/push-notifications',
    tokens: [{"old":"/push-notifications","type":0,"val":"push-notifications","end":""}],
    types: placeholder as Registry['push_notifications.store']['types'],
  },
  'push_notifications.resend': {
    methods: ["POST"],
    pattern: '/push-notifications/:id/resend',
    tokens: [{"old":"/push-notifications/:id/resend","type":0,"val":"push-notifications","end":""},{"old":"/push-notifications/:id/resend","type":1,"val":"id","end":""},{"old":"/push-notifications/:id/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['push_notifications.resend']['types'],
  },
  'analytics.index': {
    methods: ["GET","HEAD"],
    pattern: '/analytics',
    tokens: [{"old":"/analytics","type":0,"val":"analytics","end":""}],
    types: placeholder as Registry['analytics.index']['types'],
  },
  'db_backups.index': {
    methods: ["GET","HEAD"],
    pattern: '/db-backups',
    tokens: [{"old":"/db-backups","type":0,"val":"db-backups","end":""}],
    types: placeholder as Registry['db_backups.index']['types'],
  },
  'db_backups.download': {
    methods: ["GET","HEAD"],
    pattern: '/db-backups/:id/download',
    tokens: [{"old":"/db-backups/:id/download","type":0,"val":"db-backups","end":""},{"old":"/db-backups/:id/download","type":1,"val":"id","end":""},{"old":"/db-backups/:id/download","type":0,"val":"download","end":""}],
    types: placeholder as Registry['db_backups.download']['types'],
  },
  'logs_page.index': {
    methods: ["GET","HEAD"],
    pattern: '/logs',
    tokens: [{"old":"/logs","type":0,"val":"logs","end":""}],
    types: placeholder as Registry['logs_page.index']['types'],
  },
  'servers.index': {
    methods: ["GET","HEAD"],
    pattern: '/servers',
    tokens: [{"old":"/servers","type":0,"val":"servers","end":""}],
    types: placeholder as Registry['servers.index']['types'],
  },
  'servers.show': {
    methods: ["GET","HEAD"],
    pattern: '/servers/:projectId',
    tokens: [{"old":"/servers/:projectId","type":0,"val":"servers","end":""},{"old":"/servers/:projectId","type":1,"val":"projectId","end":""}],
    types: placeholder as Registry['servers.show']['types'],
  },
  'addons.index': {
    methods: ["GET","HEAD"],
    pattern: '/addons',
    tokens: [{"old":"/addons","type":0,"val":"addons","end":""}],
    types: placeholder as Registry['addons.index']['types'],
  },
  'addons.create': {
    methods: ["GET","HEAD"],
    pattern: '/addons/create',
    tokens: [{"old":"/addons/create","type":0,"val":"addons","end":""},{"old":"/addons/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['addons.create']['types'],
  },
  'addons.store': {
    methods: ["POST"],
    pattern: '/addons',
    tokens: [{"old":"/addons","type":0,"val":"addons","end":""}],
    types: placeholder as Registry['addons.store']['types'],
  },
  'addons.edit': {
    methods: ["GET","HEAD"],
    pattern: '/addons/:id/edit',
    tokens: [{"old":"/addons/:id/edit","type":0,"val":"addons","end":""},{"old":"/addons/:id/edit","type":1,"val":"id","end":""},{"old":"/addons/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['addons.edit']['types'],
  },
  'addons.update': {
    methods: ["PUT"],
    pattern: '/addons/:id',
    tokens: [{"old":"/addons/:id","type":0,"val":"addons","end":""},{"old":"/addons/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['addons.update']['types'],
  },
  'emails_page.index': {
    methods: ["GET","HEAD"],
    pattern: '/emails',
    tokens: [{"old":"/emails","type":0,"val":"emails","end":""}],
    types: placeholder as Registry['emails_page.index']['types'],
  },
  'emails_page.show': {
    methods: ["GET","HEAD"],
    pattern: '/emails/:id',
    tokens: [{"old":"/emails/:id","type":0,"val":"emails","end":""},{"old":"/emails/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['emails_page.show']['types'],
  },
  'db_backups.store': {
    methods: ["POST"],
    pattern: '/db-backups',
    tokens: [{"old":"/db-backups","type":0,"val":"db-backups","end":""}],
    types: placeholder as Registry['db_backups.store']['types'],
  },
  'db_backups.destroy': {
    methods: ["DELETE"],
    pattern: '/db-backups/:id',
    tokens: [{"old":"/db-backups/:id","type":0,"val":"db-backups","end":""},{"old":"/db-backups/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['db_backups.destroy']['types'],
  },
  'blog_posts.admin_index': {
    methods: ["GET","HEAD"],
    pattern: '/blog/manage',
    tokens: [{"old":"/blog/manage","type":0,"val":"blog","end":""},{"old":"/blog/manage","type":0,"val":"manage","end":""}],
    types: placeholder as Registry['blog_posts.admin_index']['types'],
  },
  'blog_posts.create': {
    methods: ["GET","HEAD"],
    pattern: '/blog/manage/create',
    tokens: [{"old":"/blog/manage/create","type":0,"val":"blog","end":""},{"old":"/blog/manage/create","type":0,"val":"manage","end":""},{"old":"/blog/manage/create","type":0,"val":"create","end":""}],
    types: placeholder as Registry['blog_posts.create']['types'],
  },
  'blog_posts.store': {
    methods: ["POST"],
    pattern: '/blog/manage',
    tokens: [{"old":"/blog/manage","type":0,"val":"blog","end":""},{"old":"/blog/manage","type":0,"val":"manage","end":""}],
    types: placeholder as Registry['blog_posts.store']['types'],
  },
  'blog_posts.edit': {
    methods: ["GET","HEAD"],
    pattern: '/blog/manage/:id/edit',
    tokens: [{"old":"/blog/manage/:id/edit","type":0,"val":"blog","end":""},{"old":"/blog/manage/:id/edit","type":0,"val":"manage","end":""},{"old":"/blog/manage/:id/edit","type":1,"val":"id","end":""},{"old":"/blog/manage/:id/edit","type":0,"val":"edit","end":""}],
    types: placeholder as Registry['blog_posts.edit']['types'],
  },
  'blog_posts.update': {
    methods: ["PUT"],
    pattern: '/blog/manage/:id',
    tokens: [{"old":"/blog/manage/:id","type":0,"val":"blog","end":""},{"old":"/blog/manage/:id","type":0,"val":"manage","end":""},{"old":"/blog/manage/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['blog_posts.update']['types'],
  },
  'blog_posts.destroy': {
    methods: ["DELETE"],
    pattern: '/blog/manage/:id',
    tokens: [{"old":"/blog/manage/:id","type":0,"val":"blog","end":""},{"old":"/blog/manage/:id","type":0,"val":"manage","end":""},{"old":"/blog/manage/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['blog_posts.destroy']['types'],
  },
  'blog_categories.index': {
    methods: ["GET","HEAD"],
    pattern: '/blog/manage/categories',
    tokens: [{"old":"/blog/manage/categories","type":0,"val":"blog","end":""},{"old":"/blog/manage/categories","type":0,"val":"manage","end":""},{"old":"/blog/manage/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['blog_categories.index']['types'],
  },
  'blog_categories.store': {
    methods: ["POST"],
    pattern: '/blog/manage/categories',
    tokens: [{"old":"/blog/manage/categories","type":0,"val":"blog","end":""},{"old":"/blog/manage/categories","type":0,"val":"manage","end":""},{"old":"/blog/manage/categories","type":0,"val":"categories","end":""}],
    types: placeholder as Registry['blog_categories.store']['types'],
  },
  'blog_categories.destroy': {
    methods: ["DELETE"],
    pattern: '/blog/manage/categories/:id',
    tokens: [{"old":"/blog/manage/categories/:id","type":0,"val":"blog","end":""},{"old":"/blog/manage/categories/:id","type":0,"val":"manage","end":""},{"old":"/blog/manage/categories/:id","type":0,"val":"categories","end":""},{"old":"/blog/manage/categories/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['blog_categories.destroy']['types'],
  },
  'blog_tags.index': {
    methods: ["GET","HEAD"],
    pattern: '/blog/manage/tags',
    tokens: [{"old":"/blog/manage/tags","type":0,"val":"blog","end":""},{"old":"/blog/manage/tags","type":0,"val":"manage","end":""},{"old":"/blog/manage/tags","type":0,"val":"tags","end":""}],
    types: placeholder as Registry['blog_tags.index']['types'],
  },
  'blog_tags.store': {
    methods: ["POST"],
    pattern: '/blog/manage/tags',
    tokens: [{"old":"/blog/manage/tags","type":0,"val":"blog","end":""},{"old":"/blog/manage/tags","type":0,"val":"manage","end":""},{"old":"/blog/manage/tags","type":0,"val":"tags","end":""}],
    types: placeholder as Registry['blog_tags.store']['types'],
  },
  'blog_tags.destroy': {
    methods: ["DELETE"],
    pattern: '/blog/manage/tags/:id',
    tokens: [{"old":"/blog/manage/tags/:id","type":0,"val":"blog","end":""},{"old":"/blog/manage/tags/:id","type":0,"val":"manage","end":""},{"old":"/blog/manage/tags/:id","type":0,"val":"tags","end":""},{"old":"/blog/manage/tags/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['blog_tags.destroy']['types'],
  },
  'blog_authors.index': {
    methods: ["GET","HEAD"],
    pattern: '/blog/manage/authors',
    tokens: [{"old":"/blog/manage/authors","type":0,"val":"blog","end":""},{"old":"/blog/manage/authors","type":0,"val":"manage","end":""},{"old":"/blog/manage/authors","type":0,"val":"authors","end":""}],
    types: placeholder as Registry['blog_authors.index']['types'],
  },
  'blog_authors.store': {
    methods: ["POST"],
    pattern: '/blog/manage/authors',
    tokens: [{"old":"/blog/manage/authors","type":0,"val":"blog","end":""},{"old":"/blog/manage/authors","type":0,"val":"manage","end":""},{"old":"/blog/manage/authors","type":0,"val":"authors","end":""}],
    types: placeholder as Registry['blog_authors.store']['types'],
  },
  'blog_authors.destroy': {
    methods: ["DELETE"],
    pattern: '/blog/manage/authors/:id',
    tokens: [{"old":"/blog/manage/authors/:id","type":0,"val":"blog","end":""},{"old":"/blog/manage/authors/:id","type":0,"val":"manage","end":""},{"old":"/blog/manage/authors/:id","type":0,"val":"authors","end":""},{"old":"/blog/manage/authors/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['blog_authors.destroy']['types'],
  },
  'confirm_delete_custom_user.respond': {
    methods: ["GET","HEAD"],
    pattern: '/confirm-delete-custom-user',
    tokens: [{"old":"/confirm-delete-custom-user","type":0,"val":"confirm-delete-custom-user","end":""}],
    types: placeholder as Registry['confirm_delete_custom_user.respond']['types'],
  },
  'blog_posts.index': {
    methods: ["GET","HEAD"],
    pattern: '/blog',
    tokens: [{"old":"/blog","type":0,"val":"blog","end":""}],
    types: placeholder as Registry['blog_posts.index']['types'],
  },
  'blog_posts.show': {
    methods: ["GET","HEAD"],
    pattern: '/blog/:slug',
    tokens: [{"old":"/blog/:slug","type":0,"val":"blog","end":""},{"old":"/blog/:slug","type":1,"val":"slug","end":""}],
    types: placeholder as Registry['blog_posts.show']['types'],
  },
  'team_invitations.join_page': {
    methods: ["GET","HEAD"],
    pattern: '/join',
    tokens: [{"old":"/join","type":0,"val":"join","end":""}],
    types: placeholder as Registry['team_invitations.join_page']['types'],
  },
  'auth.logout': {
    methods: ["GET","HEAD"],
    pattern: '/logout',
    tokens: [{"old":"/logout","type":0,"val":"logout","end":""}],
    types: placeholder as Registry['auth.logout']['types'],
  },
  'auth.login': {
    methods: ["POST"],
    pattern: '/api/v1/auth/login',
    tokens: [{"old":"/api/v1/auth/login","type":0,"val":"api","end":""},{"old":"/api/v1/auth/login","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/login","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/login","type":0,"val":"login","end":""}],
    types: placeholder as Registry['auth.login']['types'],
  },
  'auth.forgot_password': {
    methods: ["POST"],
    pattern: '/api/v1/auth/forgot-password',
    tokens: [{"old":"/api/v1/auth/forgot-password","type":0,"val":"api","end":""},{"old":"/api/v1/auth/forgot-password","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/forgot-password","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/forgot-password","type":0,"val":"forgot-password","end":""}],
    types: placeholder as Registry['auth.forgot_password']['types'],
  },
  'auth.reset_password': {
    methods: ["POST"],
    pattern: '/api/v1/auth/reset-password',
    tokens: [{"old":"/api/v1/auth/reset-password","type":0,"val":"api","end":""},{"old":"/api/v1/auth/reset-password","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/reset-password","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/reset-password","type":0,"val":"reset-password","end":""}],
    types: placeholder as Registry['auth.reset_password']['types'],
  },
  'auth.verify_email': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/verify-email',
    tokens: [{"old":"/api/v1/auth/verify-email","type":0,"val":"api","end":""},{"old":"/api/v1/auth/verify-email","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/verify-email","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/verify-email","type":0,"val":"verify-email","end":""}],
    types: placeholder as Registry['auth.verify_email']['types'],
  },
  'auth.verify_email_change': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/auth/verify-email-change',
    tokens: [{"old":"/api/v1/auth/verify-email-change","type":0,"val":"api","end":""},{"old":"/api/v1/auth/verify-email-change","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/verify-email-change","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/verify-email-change","type":0,"val":"verify-email-change","end":""}],
    types: placeholder as Registry['auth.verify_email_change']['types'],
  },
  'auth.resend_verification_email': {
    methods: ["POST"],
    pattern: '/api/v1/auth/verify-email/resend',
    tokens: [{"old":"/api/v1/auth/verify-email/resend","type":0,"val":"api","end":""},{"old":"/api/v1/auth/verify-email/resend","type":0,"val":"v1","end":""},{"old":"/api/v1/auth/verify-email/resend","type":0,"val":"auth","end":""},{"old":"/api/v1/auth/verify-email/resend","type":0,"val":"verify-email","end":""},{"old":"/api/v1/auth/verify-email/resend","type":0,"val":"resend","end":""}],
    types: placeholder as Registry['auth.resend_verification_email']['types'],
  },
  'users.update_profile': {
    methods: ["PUT"],
    pattern: '/api/v1/user/profile',
    tokens: [{"old":"/api/v1/user/profile","type":0,"val":"api","end":""},{"old":"/api/v1/user/profile","type":0,"val":"v1","end":""},{"old":"/api/v1/user/profile","type":0,"val":"user","end":""},{"old":"/api/v1/user/profile","type":0,"val":"profile","end":""}],
    types: placeholder as Registry['users.update_profile']['types'],
  },
  'users.update_password': {
    methods: ["PUT"],
    pattern: '/api/v1/user/password',
    tokens: [{"old":"/api/v1/user/password","type":0,"val":"api","end":""},{"old":"/api/v1/user/password","type":0,"val":"v1","end":""},{"old":"/api/v1/user/password","type":0,"val":"user","end":""},{"old":"/api/v1/user/password","type":0,"val":"password","end":""}],
    types: placeholder as Registry['users.update_password']['types'],
  },
  'users.upload_avatar': {
    methods: ["POST"],
    pattern: '/api/v1/user/avatar',
    tokens: [{"old":"/api/v1/user/avatar","type":0,"val":"api","end":""},{"old":"/api/v1/user/avatar","type":0,"val":"v1","end":""},{"old":"/api/v1/user/avatar","type":0,"val":"user","end":""},{"old":"/api/v1/user/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['users.upload_avatar']['types'],
  },
  'users.delete_avatar': {
    methods: ["DELETE"],
    pattern: '/api/v1/user/avatar',
    tokens: [{"old":"/api/v1/user/avatar","type":0,"val":"api","end":""},{"old":"/api/v1/user/avatar","type":0,"val":"v1","end":""},{"old":"/api/v1/user/avatar","type":0,"val":"user","end":""},{"old":"/api/v1/user/avatar","type":0,"val":"avatar","end":""}],
    types: placeholder as Registry['users.delete_avatar']['types'],
  },
  'sessions.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/user/sessions',
    tokens: [{"old":"/api/v1/user/sessions","type":0,"val":"api","end":""},{"old":"/api/v1/user/sessions","type":0,"val":"v1","end":""},{"old":"/api/v1/user/sessions","type":0,"val":"user","end":""},{"old":"/api/v1/user/sessions","type":0,"val":"sessions","end":""}],
    types: placeholder as Registry['sessions.index']['types'],
  },
  'sessions.revoke': {
    methods: ["POST"],
    pattern: '/api/v1/user/sessions/revoke',
    tokens: [{"old":"/api/v1/user/sessions/revoke","type":0,"val":"api","end":""},{"old":"/api/v1/user/sessions/revoke","type":0,"val":"v1","end":""},{"old":"/api/v1/user/sessions/revoke","type":0,"val":"user","end":""},{"old":"/api/v1/user/sessions/revoke","type":0,"val":"sessions","end":""},{"old":"/api/v1/user/sessions/revoke","type":0,"val":"revoke","end":""}],
    types: placeholder as Registry['sessions.revoke']['types'],
  },
  'sessions.revoke_all': {
    methods: ["POST"],
    pattern: '/api/v1/user/sessions/revoke-all',
    tokens: [{"old":"/api/v1/user/sessions/revoke-all","type":0,"val":"api","end":""},{"old":"/api/v1/user/sessions/revoke-all","type":0,"val":"v1","end":""},{"old":"/api/v1/user/sessions/revoke-all","type":0,"val":"user","end":""},{"old":"/api/v1/user/sessions/revoke-all","type":0,"val":"sessions","end":""},{"old":"/api/v1/user/sessions/revoke-all","type":0,"val":"revoke-all","end":""}],
    types: placeholder as Registry['sessions.revoke_all']['types'],
  },
  'users.delete_account': {
    methods: ["DELETE"],
    pattern: '/api/v1/user/account',
    tokens: [{"old":"/api/v1/user/account","type":0,"val":"api","end":""},{"old":"/api/v1/user/account","type":0,"val":"v1","end":""},{"old":"/api/v1/user/account","type":0,"val":"user","end":""},{"old":"/api/v1/user/account","type":0,"val":"account","end":""}],
    types: placeholder as Registry['users.delete_account']['types'],
  },
  'users.update_settings': {
    methods: ["PUT"],
    pattern: '/api/v1/user/settings',
    tokens: [{"old":"/api/v1/user/settings","type":0,"val":"api","end":""},{"old":"/api/v1/user/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/user/settings","type":0,"val":"user","end":""},{"old":"/api/v1/user/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['users.update_settings']['types'],
  },
  'users.get_settings': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/user/settings',
    tokens: [{"old":"/api/v1/user/settings","type":0,"val":"api","end":""},{"old":"/api/v1/user/settings","type":0,"val":"v1","end":""},{"old":"/api/v1/user/settings","type":0,"val":"user","end":""},{"old":"/api/v1/user/settings","type":0,"val":"settings","end":""}],
    types: placeholder as Registry['users.get_settings']['types'],
  },
  'two_factor.setup': {
    methods: ["POST"],
    pattern: '/api/v1/user/2fa/setup',
    tokens: [{"old":"/api/v1/user/2fa/setup","type":0,"val":"api","end":""},{"old":"/api/v1/user/2fa/setup","type":0,"val":"v1","end":""},{"old":"/api/v1/user/2fa/setup","type":0,"val":"user","end":""},{"old":"/api/v1/user/2fa/setup","type":0,"val":"2fa","end":""},{"old":"/api/v1/user/2fa/setup","type":0,"val":"setup","end":""}],
    types: placeholder as Registry['two_factor.setup']['types'],
  },
  'two_factor.enable': {
    methods: ["POST"],
    pattern: '/api/v1/user/2fa/enable',
    tokens: [{"old":"/api/v1/user/2fa/enable","type":0,"val":"api","end":""},{"old":"/api/v1/user/2fa/enable","type":0,"val":"v1","end":""},{"old":"/api/v1/user/2fa/enable","type":0,"val":"user","end":""},{"old":"/api/v1/user/2fa/enable","type":0,"val":"2fa","end":""},{"old":"/api/v1/user/2fa/enable","type":0,"val":"enable","end":""}],
    types: placeholder as Registry['two_factor.enable']['types'],
  },
  'two_factor.disable': {
    methods: ["POST"],
    pattern: '/api/v1/user/2fa/disable',
    tokens: [{"old":"/api/v1/user/2fa/disable","type":0,"val":"api","end":""},{"old":"/api/v1/user/2fa/disable","type":0,"val":"v1","end":""},{"old":"/api/v1/user/2fa/disable","type":0,"val":"user","end":""},{"old":"/api/v1/user/2fa/disable","type":0,"val":"2fa","end":""},{"old":"/api/v1/user/2fa/disable","type":0,"val":"disable","end":""}],
    types: placeholder as Registry['two_factor.disable']['types'],
  },
  'two_factor.verify': {
    methods: ["POST"],
    pattern: '/api/v1/user/2fa/verify',
    tokens: [{"old":"/api/v1/user/2fa/verify","type":0,"val":"api","end":""},{"old":"/api/v1/user/2fa/verify","type":0,"val":"v1","end":""},{"old":"/api/v1/user/2fa/verify","type":0,"val":"user","end":""},{"old":"/api/v1/user/2fa/verify","type":0,"val":"2fa","end":""},{"old":"/api/v1/user/2fa/verify","type":0,"val":"verify","end":""}],
    types: placeholder as Registry['two_factor.verify']['types'],
  },
  'two_factor.regenerate_recovery_codes': {
    methods: ["POST"],
    pattern: '/api/v1/user/2fa/recovery-codes',
    tokens: [{"old":"/api/v1/user/2fa/recovery-codes","type":0,"val":"api","end":""},{"old":"/api/v1/user/2fa/recovery-codes","type":0,"val":"v1","end":""},{"old":"/api/v1/user/2fa/recovery-codes","type":0,"val":"user","end":""},{"old":"/api/v1/user/2fa/recovery-codes","type":0,"val":"2fa","end":""},{"old":"/api/v1/user/2fa/recovery-codes","type":0,"val":"recovery-codes","end":""}],
    types: placeholder as Registry['two_factor.regenerate_recovery_codes']['types'],
  },
  'members.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/members',
    tokens: [{"old":"/api/v1/members","type":0,"val":"api","end":""},{"old":"/api/v1/members","type":0,"val":"v1","end":""},{"old":"/api/v1/members","type":0,"val":"members","end":""}],
    types: placeholder as Registry['members.index']['types'],
  },
  'members.invitations': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/members/invitations',
    tokens: [{"old":"/api/v1/members/invitations","type":0,"val":"api","end":""},{"old":"/api/v1/members/invitations","type":0,"val":"v1","end":""},{"old":"/api/v1/members/invitations","type":0,"val":"members","end":""},{"old":"/api/v1/members/invitations","type":0,"val":"invitations","end":""}],
    types: placeholder as Registry['members.invitations']['types'],
  },
  'members.data_access_options': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/members/data-access-options',
    tokens: [{"old":"/api/v1/members/data-access-options","type":0,"val":"api","end":""},{"old":"/api/v1/members/data-access-options","type":0,"val":"v1","end":""},{"old":"/api/v1/members/data-access-options","type":0,"val":"members","end":""},{"old":"/api/v1/members/data-access-options","type":0,"val":"data-access-options","end":""}],
    types: placeholder as Registry['members.data_access_options']['types'],
  },
  'members.update_member': {
    methods: ["PUT"],
    pattern: '/api/v1/members/:memberId',
    tokens: [{"old":"/api/v1/members/:memberId","type":0,"val":"api","end":""},{"old":"/api/v1/members/:memberId","type":0,"val":"v1","end":""},{"old":"/api/v1/members/:memberId","type":0,"val":"members","end":""},{"old":"/api/v1/members/:memberId","type":1,"val":"memberId","end":""}],
    types: placeholder as Registry['members.update_member']['types'],
  },
  'team_invitations.invite': {
    methods: ["POST"],
    pattern: '/api/v1/invitations',
    tokens: [{"old":"/api/v1/invitations","type":0,"val":"api","end":""},{"old":"/api/v1/invitations","type":0,"val":"v1","end":""},{"old":"/api/v1/invitations","type":0,"val":"invitations","end":""}],
    types: placeholder as Registry['team_invitations.invite']['types'],
  },
  'team_invitations.update_invitation': {
    methods: ["PUT"],
    pattern: '/api/v1/invitations/:invitationId',
    tokens: [{"old":"/api/v1/invitations/:invitationId","type":0,"val":"api","end":""},{"old":"/api/v1/invitations/:invitationId","type":0,"val":"v1","end":""},{"old":"/api/v1/invitations/:invitationId","type":0,"val":"invitations","end":""},{"old":"/api/v1/invitations/:invitationId","type":1,"val":"invitationId","end":""}],
    types: placeholder as Registry['team_invitations.update_invitation']['types'],
  },
  'team_invitations.invite_link': {
    methods: ["POST"],
    pattern: '/api/v1/invitations/:invitationId/invite-link',
    tokens: [{"old":"/api/v1/invitations/:invitationId/invite-link","type":0,"val":"api","end":""},{"old":"/api/v1/invitations/:invitationId/invite-link","type":0,"val":"v1","end":""},{"old":"/api/v1/invitations/:invitationId/invite-link","type":0,"val":"invitations","end":""},{"old":"/api/v1/invitations/:invitationId/invite-link","type":1,"val":"invitationId","end":""},{"old":"/api/v1/invitations/:invitationId/invite-link","type":0,"val":"invite-link","end":""}],
    types: placeholder as Registry['team_invitations.invite_link']['types'],
  },
  'team_invitations.accept': {
    methods: ["POST"],
    pattern: '/api/v1/team-invitations/accept',
    tokens: [{"old":"/api/v1/team-invitations/accept","type":0,"val":"api","end":""},{"old":"/api/v1/team-invitations/accept","type":0,"val":"v1","end":""},{"old":"/api/v1/team-invitations/accept","type":0,"val":"team-invitations","end":""},{"old":"/api/v1/team-invitations/accept","type":0,"val":"accept","end":""}],
    types: placeholder as Registry['team_invitations.accept']['types'],
  },
  'notifications.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/notifications',
    tokens: [{"old":"/api/v1/notifications","type":0,"val":"api","end":""},{"old":"/api/v1/notifications","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications","type":0,"val":"notifications","end":""}],
    types: placeholder as Registry['notifications.index']['types'],
  },
  'notifications.mark_as_read': {
    methods: ["POST"],
    pattern: '/api/v1/notifications/mark-as-read',
    tokens: [{"old":"/api/v1/notifications/mark-as-read","type":0,"val":"api","end":""},{"old":"/api/v1/notifications/mark-as-read","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications/mark-as-read","type":0,"val":"notifications","end":""},{"old":"/api/v1/notifications/mark-as-read","type":0,"val":"mark-as-read","end":""}],
    types: placeholder as Registry['notifications.mark_as_read']['types'],
  },
  'notifications.mark_all_as_read': {
    methods: ["POST"],
    pattern: '/api/v1/notifications/mark-all-as-read',
    tokens: [{"old":"/api/v1/notifications/mark-all-as-read","type":0,"val":"api","end":""},{"old":"/api/v1/notifications/mark-all-as-read","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications/mark-all-as-read","type":0,"val":"notifications","end":""},{"old":"/api/v1/notifications/mark-all-as-read","type":0,"val":"mark-all-as-read","end":""}],
    types: placeholder as Registry['notifications.mark_all_as_read']['types'],
  },
  'notifications.unread_count': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/notifications/unread-count',
    tokens: [{"old":"/api/v1/notifications/unread-count","type":0,"val":"api","end":""},{"old":"/api/v1/notifications/unread-count","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications/unread-count","type":0,"val":"notifications","end":""},{"old":"/api/v1/notifications/unread-count","type":0,"val":"unread-count","end":""}],
    types: placeholder as Registry['notifications.unread_count']['types'],
  },
  'notifications.delete': {
    methods: ["DELETE"],
    pattern: '/api/v1/notifications/:id',
    tokens: [{"old":"/api/v1/notifications/:id","type":0,"val":"api","end":""},{"old":"/api/v1/notifications/:id","type":0,"val":"v1","end":""},{"old":"/api/v1/notifications/:id","type":0,"val":"notifications","end":""},{"old":"/api/v1/notifications/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['notifications.delete']['types'],
  },
  'audits.index': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audits',
    tokens: [{"old":"/api/v1/audits","type":0,"val":"api","end":""},{"old":"/api/v1/audits","type":0,"val":"v1","end":""},{"old":"/api/v1/audits","type":0,"val":"audits","end":""}],
    types: placeholder as Registry['audits.index']['types'],
  },
  'audits.recent': {
    methods: ["GET","HEAD"],
    pattern: '/api/v1/audits/recent',
    tokens: [{"old":"/api/v1/audits/recent","type":0,"val":"api","end":""},{"old":"/api/v1/audits/recent","type":0,"val":"v1","end":""},{"old":"/api/v1/audits/recent","type":0,"val":"audits","end":""},{"old":"/api/v1/audits/recent","type":0,"val":"recent","end":""}],
    types: placeholder as Registry['audits.recent']['types'],
  },
  'health_checks': {
    methods: ["GET","HEAD"],
    pattern: '/health',
    tokens: [{"old":"/health","type":0,"val":"health","end":""}],
    types: placeholder as Registry['health_checks']['types'],
  },
  'server_stats.index': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/server-stats',
    tokens: [{"old":"/admin/api/server-stats","type":0,"val":"admin","end":""},{"old":"/admin/api/server-stats","type":0,"val":"api","end":""},{"old":"/admin/api/server-stats","type":0,"val":"server-stats","end":""}],
    types: placeholder as Registry['server_stats.index']['types'],
  },
  'debug.queries': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/debug/queries',
    tokens: [{"old":"/admin/api/debug/queries","type":0,"val":"admin","end":""},{"old":"/admin/api/debug/queries","type":0,"val":"api","end":""},{"old":"/admin/api/debug/queries","type":0,"val":"debug","end":""},{"old":"/admin/api/debug/queries","type":0,"val":"queries","end":""}],
    types: placeholder as Registry['debug.queries']['types'],
  },
  'debug.events': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/debug/events',
    tokens: [{"old":"/admin/api/debug/events","type":0,"val":"admin","end":""},{"old":"/admin/api/debug/events","type":0,"val":"api","end":""},{"old":"/admin/api/debug/events","type":0,"val":"debug","end":""},{"old":"/admin/api/debug/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['debug.events']['types'],
  },
  'debug.routes': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/debug/routes',
    tokens: [{"old":"/admin/api/debug/routes","type":0,"val":"admin","end":""},{"old":"/admin/api/debug/routes","type":0,"val":"api","end":""},{"old":"/admin/api/debug/routes","type":0,"val":"debug","end":""},{"old":"/admin/api/debug/routes","type":0,"val":"routes","end":""}],
    types: placeholder as Registry['debug.routes']['types'],
  },
  'debug.emails': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/debug/emails',
    tokens: [{"old":"/admin/api/debug/emails","type":0,"val":"admin","end":""},{"old":"/admin/api/debug/emails","type":0,"val":"api","end":""},{"old":"/admin/api/debug/emails","type":0,"val":"debug","end":""},{"old":"/admin/api/debug/emails","type":0,"val":"emails","end":""}],
    types: placeholder as Registry['debug.emails']['types'],
  },
  'debug.email_preview': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/debug/emails/:id/preview',
    tokens: [{"old":"/admin/api/debug/emails/:id/preview","type":0,"val":"admin","end":""},{"old":"/admin/api/debug/emails/:id/preview","type":0,"val":"api","end":""},{"old":"/admin/api/debug/emails/:id/preview","type":0,"val":"debug","end":""},{"old":"/admin/api/debug/emails/:id/preview","type":0,"val":"emails","end":""},{"old":"/admin/api/debug/emails/:id/preview","type":1,"val":"id","end":""},{"old":"/admin/api/debug/emails/:id/preview","type":0,"val":"preview","end":""}],
    types: placeholder as Registry['debug.email_preview']['types'],
  },
  'debug.traces': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/debug/traces',
    tokens: [{"old":"/admin/api/debug/traces","type":0,"val":"admin","end":""},{"old":"/admin/api/debug/traces","type":0,"val":"api","end":""},{"old":"/admin/api/debug/traces","type":0,"val":"debug","end":""},{"old":"/admin/api/debug/traces","type":0,"val":"traces","end":""}],
    types: placeholder as Registry['debug.traces']['types'],
  },
  'debug.trace_detail': {
    methods: ["GET","HEAD"],
    pattern: '/admin/api/debug/traces/:id',
    tokens: [{"old":"/admin/api/debug/traces/:id","type":0,"val":"admin","end":""},{"old":"/admin/api/debug/traces/:id","type":0,"val":"api","end":""},{"old":"/admin/api/debug/traces/:id","type":0,"val":"debug","end":""},{"old":"/admin/api/debug/traces/:id","type":0,"val":"traces","end":""},{"old":"/admin/api/debug/traces/:id","type":1,"val":"id","end":""}],
    types: placeholder as Registry['debug.trace_detail']['types'],
  },
  'event_stream': {
    methods: ["GET","HEAD"],
    pattern: '/__transmit/events',
    tokens: [{"old":"/__transmit/events","type":0,"val":"__transmit","end":""},{"old":"/__transmit/events","type":0,"val":"events","end":""}],
    types: placeholder as Registry['event_stream']['types'],
  },
  'subscribe': {
    methods: ["POST"],
    pattern: '/__transmit/subscribe',
    tokens: [{"old":"/__transmit/subscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/subscribe","type":0,"val":"subscribe","end":""}],
    types: placeholder as Registry['subscribe']['types'],
  },
  'unsubscribe': {
    methods: ["POST"],
    pattern: '/__transmit/unsubscribe',
    tokens: [{"old":"/__transmit/unsubscribe","type":0,"val":"__transmit","end":""},{"old":"/__transmit/unsubscribe","type":0,"val":"unsubscribe","end":""}],
    types: placeholder as Registry['unsubscribe']['types'],
  },
} as const satisfies Record<string, AdonisEndpoint>

export { routes }

export const registry = {
  routes,
  $tree: {} as ApiDefinition,
}

declare module '@tuyau/core/types' {
  export interface UserRegistry {
    routes: typeof routes
    $tree: ApiDefinition
  }
}
